databases:
  - name: djangoappdb
    plan: free
    databaseName: djangoapp
    user: clausalaerth

services:
  - type: web
    plan: free
    name: djangoapp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn djangoapp.project.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: djangoappdb_48qi
        fromDatabase:
          name: djangoappdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4