databases:
  - name: djangoappdb
    plan: free
    databaseName: djangoapp
    user: clausalaerth

services:
  - type: web
    plan: free
    name: djangoapp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: postgresql://clausalaerth:flsDz3cxI3NoWL03je97IVraaOgGlNhg@dpg-cvs9l1ur433s73c1l2qg-a.oregon-postgres.render.com/djangoappdb_48qi
        fromDatabase:
          name: djangoappdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4